mode: paper
strategy: liquidity_gap
markets: ["ETHUSDT", "BTCUSDT"]
order_size: 100.0
loop_interval_ms: 800
exchange: woofi-paper

risk:
  max_exposure_usd: 500.0
  stop_loss_pct: 1.0
  take_profit_pct: 2.0
  daily_loss_limit_pct: 5.0

strategy_params:
  liquidity_gap:
    min_spread_pct: 0.0002   # 0.0002 %  (2 bps)
    hold_time_sec: 15

backtest:
  data_dir: data/sample_candles
  timeframe: 1m
  fee_bps: 2.0

logging:
  backend: sqlite
  sqlite_path: logs/trading.db

woofi:
  poll_interval_ms: 800
  simulate_latency_ms: 50
  rest_orderbook: "https://fapi.binance.com/fapi/v1/depth?symbol={symbol}&limit=5"
  rest_bookticker: "https://fapi.binance.com/fapi/v1/ticker/bookTicker?symbol={symbol}"
  rest_ticker: "https://fapi.binance.com/fapi/v1/ticker/price?symbol={symbol}"
