mode: paper
strategy: liquidity_gap
markets: ["PERP_ETH_USDC"]
order_size: 300.0
loop_interval_ms: 600
exchange: woofi-paper

risk:
  max_exposure_usd: 300.0
  stop_loss_pct: 1.0
  take_profit_pct: 2.0
  daily_loss_limit_pct: 5.0
  max_notional_per_trade: 300.0
  max_position_age_sec: 60

strategy_params:
  liquidity_gap:
    min_spread_pct: 0.0   # 0.005 %  (2 bps)
    hold_time_sec: 15

backtest:
  data_dir: data/sample_candles
  timeframe: 1m
  fee_bps: 2.0

logging:
  backend: sqlite
  sqlite_path: logs/trading.db

woofi:
  poll_interval_ms: 800
  simulate_latency_ms: 50
  rest_orderbook: ""
  rest_bookticker: ""
  rest_ticker: ""
  # fallback that we confirmed works on Orderly testnet
  rest_pricechanges: "https://testnet-api-evm.orderly.org/v1/public/market_info/price_changes"
